name: Release new JAR to GitHub Packages
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  GITHUB_USERNAME: AntonOellerer

jobs:
  gradle-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build -x test -x check publish -Dsigning.gnupg.passphrase="${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}"
      - uses: softprops/action-gh-release@v2
        name: Release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            build/libs/*.jar
            LICENSE